In [36]:
import pandas as pd
import numpy as np

In [142]:
df = pd.read_csv('./final_df.csv',index_col=0)

In [6]:
df.hashtags = df.hashtags.fillna('')
df.hashtags = [x.split(' ') for x in df.hashtags]

In [136]:
#중복값 체크
for idx,i in enumerate(df.hashtags):
    if len(set(i)) != len(i):
        print(idx)

In [28]:
token_ls = []
for i in df.hashtags:
    for j in i:
        token_ls.append(j)
token_ls.sort()

token_set_ls = []
for i in df.hashtags:
    for j in i:
        if j not in token_set_ls:
            token_set_ls.append(j)
token_set_ls.sort()

In [94]:
print('전체 hashtags의 token의 개수:', len(token_ls))
print('hashtags의 unique token의 개수:', len(token_set_ls))

전체 hashtags의 token의 개수: 147126
hashtags의 unique token의 개수: 24922

## token의 빈도

In [58]:
tmp = np.zeros(len((token_set_ls)))

for idx,i in enumerate(token_set_ls):
    tmp[idx] = token_ls.count(i)  

val_ls = [int(x) for x in tmp]

token_df = pd.DataFrame(val_ls, index = token_set_ls, columns = {'count'})

hashtag_token_df = token_df.sort_values(by = 'count', ascending = False)

In [147]:
hashtag_token_df.head(50)

                    count
fashion              3813
style                2711
ootd                 2400
fashionblogger       2070
instafashion         1558
fashionista          1460
streetstyle          1374
outfit               1369
instagood            1157
fashionable          1078
fashionstyle         1042
stylish              1027
outfitoftheday       1005
styleblogger         1003
moda                  962
love                  933
model                 917
look                  863
streetwear            849
photooftheday         840
streetfashion         827
instastyle            764
fashionweek           761
photography           700
trend                 684
                      670
fashiongram           650
beautiful             635
fashionblog           634
fashionaddict         596
beauty                586
summer                580
fashiondiaries        574
fashionpost           563
fashioninspiration    549
lookoftheday          548
dress                 543
blogger               521
picoftheday           519
lookbook              511
girl                  498
mensfashion           485
cute                  480
follow                453
instagram             447
fashionshow           440
lifestyle             438
shopping              430
fashioninsta          425
dailylook             405